export const MEMBERSHIP_PLANS = [
  {
    id: 'silver',
    name: 'Silver Plan – Basic Care (Monthly)',
    description: 'Ideal for busy customers needing basic upkeep.',
    features: [
      '4 washes/month (once a week).',
      'Exterior wash with eco-friendly shampoo.',
      'Tyre cleaning & air check.',
      'Quick service.',
    ],
    price: 1,
    duration: 'month',
    popular: false,
  },
  {
    id: 'gold',
    name: 'Gold Plan – Standard Care (Monthly)',
    description: 'Enhanced care for a consistently clean vehicle.',
    features: [
      '8 washes/month (twice a week).',
      'Exterior wash + basic interior vacuuming.',
      'Premium shampoo & waxing once a month.',
      'Dashboard, windows & mirrors cleaning.',
      'Tyre polishing for a refined look.',
    ],
    price: 899,
    duration: 'month',
    popular: true,
  },
  {
    id: 'platinum',
    name: 'Platinum Plan – Premium Care (Monthly)',
    description: 'Comprehensive and priority care for ultimate vehicle maintenance.',
    features: [
      '12 washes/month (three times a week) or priority on-demand visits.',
      'Full exterior + deep interior cleaning.',
      'Wax coating & paint protection twice a month.',
      'Vacuuming of seats, carpets & mats.',
      'Engine bay dust cleaning.',
      '1 complimentary full detailing session each month.',
    ],
    price: 1499,
    duration: 'month',
    popular: false,
  },
];